name: Hexo CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出源码
        uses: actions/checkout@v2

      - name: 设置 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: 安装依赖
        run: npm install

      - name: 生成静态文件
        run: npm run build

      - name: 部署到 GitHub Pages
        env:
          PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_REPOSITORY: Jpl-hub/Jpl-hub.github.io
          PUBLISH_BRANCH: main
          PUBLISH_DIR: ./public
        run: |
          npm install hexo-deployer-git --save
          npx hexo-deployer-git --repo https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/Jpl-hub/Jpl-hub.github.io.git --branch main --dir ./public
