name: Hexo CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出源码
        uses: actions/checkout@v2

      - name: 设置 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: 安装 Hexo CLI
        run: |
          npm install -g hexo-cli
          sudo chmod +x /usr/local/bin/hexo

      - name: 安装项目依赖
        run: npm install

      - name: 生成静态文件
        run: hexo generate

      - name: 部署到 GitHub Pages
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --global user.name "Jpl-hub"
          git config --global user.email "J7777777772022@outlook.com"
          npx hexo deploy
