name: James's Blog CI/CD

on:
  push:
    branches: [main]
    paths:
      - '*.json'
      - '**.yml'
      - '**/source/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name "Jpl-hub"
          git config --global user.email "J7777777772022@outlook.com"

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          npm install hexo-cli -g
          hexo deploy
